# -*- coding: utf-8 -*-
# vim: ft=yaml
---
################################################################################
# NOTE: This file is UNMAINTAINED; it is provided for references purposes only.
#       No guarantees are tendered that this structure will work after 2020.
################################################################################
# * https://en.wikipedia.org/wiki/Travis_CI:
#   - "... free open-source plans were removed in [sic] the end of 2020"
#   - https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
#   - https://ropensci.org/technotes/2020/11/19/moving-away-travis/
################################################################################
{%- from tplroot ~ "/libcimatrix.jinja" import format_ci_matrix with context %}

{%- macro format_allow_failures(use_single_job_for_linters) %}
{%-   filter indent(2) %}
{%-     if not use_single_job_for_linters %}
allow_failures:
  - env: Lint_rubocop
fast_finish: true
{%-     endif %}
{%-   endfilter %}
{%- endmacro %}

{%- macro format_rubocop_linter() %}
{%-   filter indent(8) %}
# Install and run `rubocop`
- gem install rubocop
- rubocop -d
{%-   endfilter %}
{%- endmacro %}

{#-   Prepare variables used for linters #}
{%- set comment_linters = '# Run all of the linters in a single job' %}
{%- set name_linters = 'Lint: salt-lint, yamllint, rubocop, shellcheck & commitlint' %}
{%- if not travis.use_single_job_for_linters %}
{%-   set comment_linters = comment_linters ~ ' (except `rubocop`)' %}
{%-   set name_linters = 'Lint: salt-lint, yamllint, shellcheck & commitlint' %}
{%- endif %}
{#-   Prepare variable used for `saltcheck` #}
{%-   set use_saltcheck = False %}
{%-   if semrel_formula in ['cron'] %}
{%-     set use_saltcheck = True %}
{%-   endif %}
## Machine config
os: 'linux'
arch: 'amd64'
dist: '{{ travis.dist }}'
version: '~> 1.0'

## Language and cache config
language: 'ruby'
cache: 'bundler'

{#- Specifically avoiding `and not use_github_actions`, since this is only used for #}
{#- formulas which don't work in GitLab CI but used to work in Travis CI            #}
{#- if platforms and not use_cirrus_ci and not use_github_actions #}
{%- if platforms and not use_cirrus_ci %}

## Services config
services:
  - docker
{%-   set travis_addons = travis.addons %}
{%-   if travis_addons %}

## Addons config
# yamllint disable rule:indentation
addons:
{%-     filter indent(2) %}
{{ travis_addons | yaml(False) }}
{%-     endfilter %}
# yamllint enable rule:indentation
{%-   endif %}

## Script to run for the test stage
script:
  {%- for pre_cmd in script_kitchen.pre %}
  - {{ pre_cmd }}
  {%- endfor %}
  {%- if use_saltcheck %}
  # yamllint disable rule:line-length
  # Converge and verify the instance; `saltcheck` relies upon the `converge` as well
  {%- endif %}
  - {{ script_kitchen.bin }} {{ script_kitchen.cmd }} "${INSTANCE}"
  {%- for post_cmd in script_kitchen.post %}
  - {{ post_cmd }}
  {%- endfor %}
  {%- if use_saltcheck %}
  # If a `master` instance, get the appropriate version of `saltcheck.py` (temporary)
  {%-   if semrel_formula in ['cron'] %}
  # Likewise, use a custom `cron.py` temporarily until the upstream PR is merged:
  # - https://github.com/saltstack/salt/pull/55016
  {%-   endif %}
  - if [ ! -z $(echo "${INSTANCE}" | grep \\-master-) ]; then
      bin/kitchen exec "${INSTANCE}" -c
        "sudo curl -o \$(find /usr/lib/ -type d -name modules | grep packages/salt/modules)/saltcheck.py
        https://raw.githubusercontent.com/myii/salt/fix/add-retcode/salt/modules/saltcheck.py";
      {%- if semrel_formula in ['cron'] %}
      bin/kitchen exec "${INSTANCE}" -c
        "sudo curl -o \$(find /usr/lib/ -type d -name modules | grep packages/salt/modules)/cron.py
        https://raw.githubusercontent.com/myii/salt/fix/add-retcode/salt/modules/cron.py";
      {%- endif %}
    fi
  # If a `master` instance, run all of the `saltcheck` tests
  - if [ ! -z $(echo "${INSTANCE}" | grep \\-master-) ]; then
      bin/kitchen exec "${INSTANCE}" -c
        "sudo salt-call
        --config-dir=/tmp/kitchen/etc/salt
        saltcheck.run_state_tests
        cron check_all=True";
    fi
  # yamllint enable rule:line-length
  {%- endif %}
{%- endif %}

## Stages and jobs matrix
stages:
  - test
  # # As part of the switch away from Travis CI, ensure that the `release` stage
  # # is not run inadvertently
  # - name: 'release'
  #   if: 'branch = master AND type != pull_request'
jobs:
  {{- format_allow_failures(travis.use_single_job_for_linters) }}
  include:
    ## Define the test stage that runs the linters (and testing matrix, if applicable)

    {{ comment_linters }}
    - language: 'node_js'
      node_js: 'lts/*'
      env: 'Lint'
      name: '{{ name_linters }}'
      before_install: 'skip'
      script:
        {#- Prepare variable used for `pip` #}
        {%- set pip_cmd = 'pip' %}
        # Install and run `salt-lint`
        - {{ pip_cmd }} install --user salt-lint
        - git ls-files -- '*.sls' '*.jinja' '*.j2' '*.tmpl' '*.tst'
                        | xargs salt-lint
        # Install and run `yamllint`
        # Need at least `v1.17.0` for the `yaml-files` setting
        - {{ pip_cmd }} install --user yamllint>=1.17.0
        - yamllint -s .
        {%- if travis.use_single_job_for_linters %}
        {{-   format_rubocop_linter() }}
        {%- endif %}
        # Run `shellcheck` (already pre-installed in Travis)
        - shellcheck --version
        - git ls-files -- '*.sh' '*.bash' '*.ksh'
                        {%- for path in shellcheck.exclude_paths %}
                        | grep -v '{{ path }}'
                        {%- endfor %}
                        | xargs shellcheck
        # Install and run `commitlint`
        - npm i -D @commitlint/config-conventional
                   @commitlint/travis-cli
        {#- Note: `--verbose` doesn't work yet, upstream issue created:          #}
        {#-   - https://github.com/conventional-changelog/commitlint/issues/1695 #}
        - commitlint-travis{{- ' --verbose' if semrel_formula == 'ssf' else '' }}

    {%- if not travis.use_single_job_for_linters %}
    # Run the `rubocop` linter in a separate job that is allowed to fail
    # Once these lint errors are fixed, this can be merged into a single job
    - language: node_js
      node_js: lts/*
      env: Lint_rubocop
      name: 'Lint: rubocop'
      before_install: skip
      script:
        {{-   format_rubocop_linter() }}
    {%- endif %}

    # Run `pre-commit` linters in a single job
    - language: 'python'
      env: 'Lint_pre-commit'
      name: 'Lint: pre-commit'
      before_install: 'skip'
      cache:
        directories:
          - $HOME/.cache/pre-commit
      script:
        # Install and run `pre-commit`
        - {{ pip_cmd }} install pre-commit==2.7.1
        - pre-commit run --all-files --color always --verbose
        - pre-commit run --color always --hook-stage manual --verbose commitlint-travis

    {%- if platforms and not use_cirrus_ci %}

    ## Define the rest of the matrix based on Kitchen testing
    # Make sure the instances listed below match up with
    # the `platforms` defined in `kitchen.yml`
    {%-   if semrel_formula == 'template' %}
    # NOTE: Please try to select up to six instances that add some meaningful
    #       testing of the formula's behaviour. If possible, try to refrain from
    #       the classical "chosing all the instances because I want to test on
    #       another/all distro/s" trap: it will just add time to the testing (see
    #       the discussion on #121).  As an example, the set chosen below covers
    #       the most used distros families, systemd and non-systemd and the latest
    #       three supported Saltstack versions with python2 and 3.
    #       As for `kitchen.yml`, that should still contain all of the platforms,
    #       to allow for comprehensive local testing
    #       Ref: https://github.com/saltstack-formulas/template-formula/issues/118
    #       Ref: https://github.com/saltstack-formulas/template-formula/issues/121
    {%-   endif %}
    {{- format_ci_matrix(platforms, inspec_suites_kitchen, inspec_suites_matrix, platforms_matrix, platforms_matrix_commented_includes, semrel_formula, use_new_travis_format=True) }}
    {%- endif %}

    {%- if semrel_formula == 'template' %}
    # <REMOVEME

    # Test the conversion of `template-formula` into another formula
    # ready for development
    - env: 'Conversion'
      name: 'Test: bin/convert-formula.sh'
      script:
        - export CONVERTED=test-the-use_this_template-button
        - git clone . tmp/"$CONVERTED"-formula
        - cd tmp/"$CONVERTED"-formula
        - pyenv global 3.8
        - pip install pre-commit==2.7.1
        - bin/install-hooks
        - DEBUG=true bin/convert-formula.sh "$CONVERTED"
        - '[ $(git rev-list HEAD --count) -eq 2 ]'
        # Quick visual check that correct files have been updated
        - git show --pretty="" --name-status
        - bin/kitchen verify default-debian-10-tiamat-py3
    # REMOVEME>
    {%- endif %}

    ## Define the release stage that runs `semantic-release`
    - stage: 'release'
      language: 'node_js'
      node_js: 'lts/*'
      env: 'Release'
      name: 'Run semantic-release inc. file updates to AUTHORS, CHANGELOG & FORMULA'
      before_install: 'skip'
      script:
        # Update `AUTHORS.md`
        - export MAINTAINER_TOKEN=${GH_TOKEN}
        - go get github.com/myii/maintainer
        - maintainer contributor

        # Install all dependencies required for `semantic-release`
        - npm i -D @semantic-release/changelog@3
                   @semantic-release/exec@3
                   @semantic-release/git@7
      deploy:
        provider: 'script'
        # Opt-in to `dpl v2` to complete the Travis build config validation (beta)
        # * https://docs.travis-ci.com/user/build-config-validation
        # Deprecated `skip_cleanup` can now be avoided, `cleanup: false` is by default
        edge: true
        # Run `semantic-release`
        script: 'npx semantic-release@15.14'
{%- if semrel_formula == 'template' %}
# <REMOVEME
{%- endif %}

# Notification options: `always`, `never` or `change`
{#- TODO: Move this to `defaults.yaml` & `formulas.yaml` #}
{%- set ignore_pull_requests = 'false' if semrel_formula in ['ssf'] else 'true' %}
notifications:
  webhooks:
    if: 'repo = {{ owner }}/{{ formula }}'
    urls:
      - {{ 'https://{}/api/v1/external/travis?{}&{}&{}&{}'.format(
             'saltstack-formulas.zulipchat.com',
             'api_key=HsIq3o5QmLxdnVCKF9is0FUIpkpAY79P',
             'stream=CI',
             'topic={}%2F{}'.format(owner, formula),
             'ignore_pull_requests={}'.format(ignore_pull_requests),
        ) }}
    on_success: always  # default: always
    on_failure: always  # default: always
    on_start: always    # default: never
    on_cancel: always   # default: always
    on_error: always    # default: always
{%- if semrel_formula == 'template' %}
# REMOVEME>
{%- endif %}
